name: DPG-Toy
method:
  _target_: algo.dpg.DPG
  diffusion_scheduler_config:
    num_steps: 100
    schedule: 'linear'
    timestep: 'poly-7'
    sigma_min: 0.01
    sigma_final: 0
  guidance_scale: 1.0
  num_mc_samples: 100
  batch_size: 100
