name: DPS
method:
  _target_: algo.dps.DPS
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'vp'
    timestep: 'vp'
    scaling: 'vp'
  guidance_scale: 0.5  # Lower scale for better stability on toy image problems
  sde: True

method:
  _target_: algo.dps.DPS
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'vp'
    timestep: 'vp'
    scaling: 'vp'
  guidance_scale: 0.5  # Lower scale for better stability on toy image problems
  sde: True







