name: PiGDM
method:
  _target_: algo.pigdm.PiGDM
  scheduler_config:
    num_steps: 100
    sigma_max: 100
    sigma_min: 0.01
    schedule: 'sqrt'
    timestep: 'log'
      # schedule: 'vp'
    # timestep: 'vp'
    # scaling: 'vp'
  eta: 0.2
  noisy: True

