name: PiGDM-Toy
method:
  _target_: algo.pigdm.PiGDM
  scheduler_config:
    num_steps: 100
    sigma_max: 5.0
    sigma_min: 0.01
    schedule: 'linear'
    timestep: 'poly-7'
  eta: 0.2
  noisy: True
