name: SCG
method:
  _target_: algo.scg.SCG
  diffusion_scheduler_config:
    num_steps: 1000
    schedule: 'vp'
    timestep: 'vp'
    scaling: 'vp'
  threshold: 0.25
  num_candidates: 512
  batch_size: 64
